### ISSUE TITLE
[Fix]: linesandplanes-vectorequation

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#100]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-vectorequation

### What type of applet is this?

Interactive applet 2D

### Link to applet

https://openla.ewi.tudelft.nl/applet/lines_and_planes/vector-equation

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234626888-b588164a-a4b3-40c7-a297-08ec4198fd3b.png)

### Requirements

None

### What elements are interactive?

Scale v0 and v1

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by ChristopheTUD** [comment]
- Scaling of v0 and v1 is not working yet
- Does it make sense to scale those two? That is a very indirect way of changing the direction vector, u, which I think is the more interesting one. When scaling v0 and v1 you also force their direction to be fixed...
- Personally I would have gone for a fixed v0 and a u-vector (the one at the origin) which you can drag, changing the line as you do this.
