### ISSUE TITLE
[New image]: DeterminantsGeometric - detgeometric-linearity

### ISSUE THREAD

**Issue by VandeBult** [PRIME-TU-Delft/Open-LA-Applets#106]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter5/DeterminantsGeometric.html#fig-detgeometric-linearity

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

![Image](https://github.com/PRIME-TU-Delft/Open-LA-Applets/assets/25432790/d6753395-6e21-4a12-9819-df6ca245ea4a)

Yes, Dennis has created a static image

### Static image

https://dbalague.pages.ewi.tudelft.nl/openlabook/_images/Fig-DetGeometric-SumRule.svg

### Requirements

None

### What elements are interactive?

For the left image you want to be able to press a "play" button after which the triangle ABD shifts to OEC.
(Would change caption to "The area of OABC plus area of CBDE equals the area of OADE")

Right image same idea with triangles OGC and AEF.

(Not checked with colleagues yet).

### Steps to completion:

- [x] assign yourself & check labels
- [x] implement new applet described above
- [x] embed the image in the book (with review status)
- [x] get feedback from the math teachers
- [x] get feedback from writers
- [x] remove review status in book

**Comment by yustarandomname** [comment]
- [ ] Make these applet be interactive with the new animation slide show controls as described in #245
