### ISSUE TITLE
[New image]: EigenvaluesEigenvectors fig-eigenvalues-eigenvector-no-eigenvector

### ISSUE THREAD

**Issue by VandeBult** [PRIME-TU-Delft/Open-LA-Applets#107]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter6/EigenvaluesEigenvectors.html#fig-eigenvalues-eigenvector-no-eigenvector

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

https://dbalague.pages.ewi.tudelft.nl/openlabook/_images/Fig-Eigenvalues-Eigenvector-no-Eigenvector.svg

### Requirements

The matrix is from the example A = [1 4 \\ 1 1]

### What elements are interactive?

The picture is slightly different; shown are u (norm 1) and Au. With a slider you can rotate u around (so the slider is like theta). And then you can easily see when Au and u point in the same direction.

Maybe with a click to the correct point on the correct eigenvectors and a fireworks show ;-). 

### Steps to completion:

- [ ] assign yourself & check labels
- [ ] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by VandeBult** [comment]
Misschien herhalen bij Figure 6.2 met andere matrix?

**Comment by yustarandomname** [comment]
It is a duplicate of #149. Overthere the issue is better described. Thus, this issue will be closed
