### ISSUE TITLE
[Fix]: lines_and_planes/normal_equation_plane

### ISSUE THREAD

**Issue by VandeBult** [PRIME-TU-Delft/Open-LA-Applets#108]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html

### Direct link to the applet

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-normalequationplane

### What type of applet is this?

Interactive applet 3D

### What needs to change?

Minder labels op de assen, nu zijn ze slecht leesbaar.
Beginpositie als in 
https://openla.ewi.tudelft.nl/applet/lines_and_planes/normal_equation_plane?position=-10.82,5.42,12.39&zoom=29.00
Niet roteerbaar.

### Steps to completion:

- [ ] assign yourself & check labels
- [ ] implement changes described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by VandeBult** [comment]
Ik wil het wel roteerbaar!

**Comment by ahensbergen** [comment]
Applaus namens  André en René.  Dit plaatje is er flink op vooruitgegaan.
De bullets kunnen wat ons betreft kleiner en zwart,  of, als de kleur aangehouden worden ook de letters P, enz die kleur geven.
Het vager maken van de bullets 'onder het vlak' blijven we onnodig (René) dan wel storend (André) vinden.  Het zijn dimensieloze PUNTEN ja. NB  de asse nachter het vlak vervagen is WEL oké.

Nog steeds:  de  vector n in het plaatje moet **boldface**

Bij dit plaatje kan je door roteren laten zien dat O niet in het vlak ligt. Dat is goed.
Het plaatje daarvóór  (waarvan we eerste zeiden: NIET AANPASSEN) liever goede stand kiezen en NIET roteerbaar.

**Comment by yustarandomname** [comment]
Is duidelijk. Zal ik morgen wel kunnen implementeren 😀

**Comment by yustarandomname** [comment]
@TeunJa vindt deze stand mooier https://openla.ewi.tudelft.nl/applet/lines_and_planes/normal_equation_plane?position=-11.00,5.40,12.40&zoom=46.00

**Comment by yustarandomname** [comment]
is resolved
