### ISSUE TITLE
[Fix]: lines_and_planes/normal_equation_plane_origin

### ISSUE THREAD

**Issue by ahensbergen** [PRIME-TU-Delft/Open-LA-Applets#111]
### Link to paragraph
https://prime.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html

### Direct link to the applet

https://openla.ewi.tudelft.nl/applet/lines_and_planes/normal_equation_plane_origin?position=-7.24,-2.82,15.48&zoom=29.00

### What type of applet is this?

Interactive applet 3D

### What needs to change?

0) WACHT MET AANPASSEN:  wellicht dat het vlak dat niet door 0 gaat voldoende is .

1) Beginstand instellen zoals nu aangegeven.

2)  x en -x verwisselen  (terwijl vlak visueel hetzelfde blijft)

3)  Vector n als bold zetten

4)  Q niet door het punt heen.  Dat het punt een bolletje wordt, snap ik.  
     Maar het gedeelde 'onder' het vlak vager maken is ongewenst.  Misschien  Q  groen maken?

5)  Minder tickmarks als ze te dicht op elkaar komen.  Tickmarks kunnen hier zelfs weg!

### Steps to completion:

- [ ] assign yourself & check labels
- [ ] implement changes described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by BEvanGelderen** [comment]
Wat goed @ahensbergen , dank je wel hiervoor!
