### ISSUE TITLE
René and André think:  this picture is hopeless.  

### ISSUE THREAD

**Issue by ahensbergen** [PRIME-TU-Delft/Open-LA-Applets#117]
### What needs to change?

It does NOT illustrate the construction of a param vector equation of a plane.
For one thing:  v0 is not in the picture.
2) P, Q and R are indicated (with 'bullets' that are not very nice and have irrelevant colors).
3) Het 'hele' vlak afbeelden helpt ook niet.  Liever het kwart waarbij r en s  (zie tekst) >= 0 zijn.
sorry about the inconsistency in de taal.
4)  Draaibaar maken voegt hiet echt helemaal niks toe.
5) ALS je het wilt 'interactiveren' dan zou je hoogstens met r en s kunnen spelen.

6) Zelfs met een goede 'fixed'  startpositie wordt het nog  niet duidelijk.

Overigens,  het originele plaatje (zoals nog te zien op Overleaf) heeft een flink deel van dezelfde tekortkomingen.
Vinden wij.

**Comment by yustarandomname** [comment]
This issue is closed due to too little context given
