### ISSUE TITLE
lines_and_planes/two_disjoint_planes

### ISSUE THREAD

**Issue by ahensbergen** [PRIME-TU-Delft/Open-LA-Applets#118]
### What needs to change?

Nou ja,  leuk speelgoed.  Meer is het niet.  Het legt wat ons betreft niks uit.
Het tekstbalkje boven  (wat verschijnt als je op i drukt) voegt niks toe.  En ALS het blijft dan  1x+1y  vervangen door x+y  (twee keer).

Is het mogelijk om het plaatje even stil te laten staan du moment dat de vlakken samenvallen? (vindt André leuk)

**Comment by yustarandomname** [comment]
haal sliders weg
