### ISSUE TITLE
[Fix]:   (Fig.133)  lines_and_planes/plane_line_intersection

### ISSUE THREAD

**Issue by ahensbergen** [PRIME-TU-Delft/Open-LA-Applets#123]
### What type of applet is this?

Static image

### What needs to change?

Dit lijkt ons een redelijke stand:

https://openla.ewi.tudelft.nl/applet/lines_and_planes/plane_line_intersection?position=7.29,-4.94,14.91&zoom=37.00&sliders=-0.60,0.20,0.80

Verder weer:  (1) al die kleuren :-(    (2)  Balkjes weg   (we doen nog niet rekenen aan doorsnden)  (

### Steps to completion:

- [x] assign yourself & check labels
- [x] implement changes described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by yustarandomname** [comment]
kleuren zijn standaard kleuren van de TU Delft (https://www.tudelft.nl/huisstijl/bouwstenen/kleur). Het boek krijgt de zelfde kleuren
