### ISSUE TITLE
[FIX]: lines_and_planes/parametric_line_space

### ISSUE THREAD

**Issue by ahensbergen** [PRIME-TU-Delft/Open-LA-Applets#124]
### What needs to change?

Kijk,  hier worden we dus wel blij van.  De slider is  PRIMA HIER.

Suggestie voor beginstand:
  https://openla.ewi.tudelft.nl/applet/lines_and_planes/parametric_line_space?position=8.76,6.95,13.22&zoom=38.00&sliders=2.00

Verbeterpuntjes:
(1) Vectoren doen we al tijden **boldface**
(2) Roteren voegt ECHT NIKS TOE   (bij geschikte beginstand)

**Comment by yustarandomname** [comment]
Volgens een peiling onder studenten blijkt dat 3D-applets die niet draaibaar zijn vaak moeilijk te begrijpen waar lijnen en vlakken lopen, omdat de diepte moeilijk in te schatten is. Daarom is gekozen om een begin scherm te hebben die niet draaibaar is maar studenten kunnen kiezen om draaien aan te zetten als ze dat fijn vinden.

**Comment by ahensbergen** [comment]
OKAY

**Comment by BEvanGelderen** [comment]
Iets kortere Z as zou ik wel mooi vinden!
