### ISSUE TITLE
[Issue]: dot_product/diagonal_parallelogram | Suggestion for interactivity

### ISSUE THREAD

**Issue by ChristopheTUD** [PRIME-TU-Delft/Open-LA-Applets#140]
### What needs to change?

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#fig-innerproduct-diagonal-parallelogram
Figure 1.9: deze kan interactief. Het is niet zo eenvoudig te zien dat de twee diagonalen aan de linkerkant verschillende lengte hebben, en je wil de figuur liefst ook niet overladen door cirkels bij te tekenen of wat dan ook.
Ik zou de vectoren v en w draggable maken (altijd startend in de oorsprong, op een grid) en dan de lengte van v+w en van v-w laten berekenen.

**Comment by yustarandomname** [comment]
- [ ] zorg dat punten "snappen" op het grid
- [ ] 


## Wat moet verandert worden aan de text
"Well, look at [Figure 1.9](https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#fig-innerproduct-diagonal-parallelogram):" -> Maak eerst duidelijk dat we generaliseren in R2.

**Comment by yustarandomname** [comment]
Version one is created

**Comment by yustarandomname** [comment]
- [ ] vectoren in zelfde kleur 
- [ ] Laten staan van linker plaatje no interactief
- [ ] Begin links: iets meer verschillend maken
- [ ] display afstanden v+w >,<,= v-w
