### ISSUE TITLE
[Issue]: rotisdoublerefl

### ISSUE THREAD

**Issue by ChristopheTUD** [PRIME-TU-Delft/Open-LA-Applets#145]
### What needs to change?

![Image](https://github.com/PRIME-TU-Delft/Open-LA-Applets/assets/25432790/a10d2f25-5212-4702-8fbf-2905ada0da22)

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter3/GeometryofLinearTransformations.html#fig-geomlintrans-rotisdoublerefl
Figure 3.12: kan interactief. Bijvoorbeeld phi met schuifknop regelbaar, L1 draggable op zo'n manier dat L2 altijd een hoek $\theta$/2 maakt met L1. Of v dan ook beweegbaar moet zijn, dat zou kunnen (als het dan nog wat overzichtelijk is tenminste, dat is mss niet echt nodig).

**Comment by yustarandomname** [comment]
Comment van Nicolaas wordt verwacht.

**Comment by yustarandomname** [comment]
Phi veranderen betekend dat l_1 & l_2 naar links schuiven als phi groter wordt. Verder een lijn van oorsprong naar $T_l_1(v)$ zoals geschetst

**Comment by yustarandomname** [comment]
![image](https://github.com/PRIME-TU-Delft/Open-LA-Applets/assets/25432790/11337869-6231-49a6-bfee-a18a459fb53d)
