### ISSUE TITLE
[Issue]: Complex numbers

### ISSUE THREAD

**Issue by ChristopheTUD** [PRIME-TU-Delft/Open-LA-Applets#148]
### What needs to change?

https://dbalague.pages.ewi.tudelft.nl/openlabook/Appendices/ComplexNumbers.html#fig-complexnumbers-threesolfig
Figure 10.11: kan interactief. Je zou z^m=a+bi kunnen laten oplossen, waarbij de gebruiker m kan ingeven (_geheel_, van 1 tot 9 of zo), en a en b. Getekend worden dan de m oplossingen, telkens met een hoek 2pi/m ertussen.
Nu is figure 10.11 wel de figuur die hoort bij example 10.15, dus misschien is het dan beter dit als nieuwe figuur te hebben na de veralgemening (de zes stappen onder deze figuur).

**Comment by ChristopheTUD** [comment]
Suggestie André: animatie. Dus laat student wel n ingeven (tot n=8 bvb) en het rechterlid. Laat dan eerst een cirkel tekenen met de juiste straal (n-de machtswortel uit modulus van rechterlid). Dan deel je het argument in n. Dan heb je één oplossing. Daarna roteer je deze nog n-1 keer over een hoek 2pi/n. Klaar!

**Comment by yustarandomname** [comment]
Interactief plaatje komt onder punt 6. (https://dbalague.pages.ewi.tudelft.nl/openlabook/Appendices/ComplexNumbers.html#fig-complexnumbers-threesolfig:~:text=Combine%20the%20solution,solutions.)

**Comment by yustarandomname** [comment]
Output of the applet does not correspond to wolfram alpha output 



![Image](https://github.com/user-attachments/assets/b393a600-fd16-4a67-9313-e48467958059)

**Comment by BEvanGelderen** [comment]
Maybe it might help to have a look at this applet https://prime-applets.ewi.tudelft.nl/apps/calculus/complex .

**Comment by yustarandomname** [comment]
> Output of the applet does not correspond to wolfram alpha output
> 
> ![Image](https://github.com/user-attachments/assets/b393a600-fd16-4a67-9313-e48467958059)

This issue has been resolved and pushed
