### ISSUE TITLE
[Issue]: suggestie voor nieuwe geanimeerde figuur bij eigenvectoren: 

### ISSUE THREAD

**Issue by ChristopheTUD** [PRIME-TU-Delft/Open-LA-Applets#149]
### What needs to change?

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter6/EigenvaluesEigenvectors.html#fig-eigenvalues-eigenvector-no-eigenvector

Geen prioriteit want gaat over eigenwaarden en eigenvectoren, dus wordt pas vanaf Q2 gebruikt.

André's idee: fix een 2 bij 2 matrix, bijvoorbeeld A = [[7/3, -2/3], [2/3, 2/3]]. Die heeft eigenwaarde L_1 = 2 met eigenvector v_1=[2,1] en eigenwaarde L_2=1 met eigenvector v_2=[1,2]. 

Wat er getekend moet worden: start met de eenheidsvector e_1=[1,0], met Ae_1 = [7/3, 2/3]. Teken beide vectoren. Laat dan een vector v in tegenwijzerzin ronddraaien over de eenheidscirkel (startend bij e_1) en teken telkens ook Av. Je ziet dan dat v en Av in het begin niet samenvallen, maar na een tijdje wel, namelijk exact wanneer v in de richting van v_1 ligt. Bovendien zie je dan dat Av een factor L_1 groter is. De vector v draait verder, waarbij v niet meer samenvalt met Av, tot plots v_2 bereikt wordt, waar Av weer wel in dezelfde richting als v loopt.

Eventueel kunnen v_1 en v_2 in beeld blijven staan nadat v ze gepasseerd is.

**Comment by yustarandomname** [comment]
@ChristopheTUD of @VandeBult zou een van jullie een tekening kunnen maken van deze applet. Is nog niet helemaal duidelijk wat het leerdoel hiervan is

**Comment by yustarandomname** [comment]
![Image](https://github.com/user-attachments/assets/9214cff6-266e-4c5a-b846-b81c337396bc)

**Comment by yustarandomname** [comment]
![Image](https://github.com/user-attachments/assets/de3eaee3-54eb-4777-acbb-705b09d38cc1)
