### ISSUE TITLE
[Issue]: geanimeerde figuur bij determinanten

### ISSUE THREAD

**Issue by ChristopheTUD** [PRIME-TU-Delft/Open-LA-Applets#151]
### What needs to change?

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter5/DeterminantsGeometric.html#fig-detgeometric-linearity

Geen prio want determinanten dus pas in Q2.

Veel te lastig om te beschrijven. Idee is om de twee figuren die er nu staan, stap per stap op te bouwen en gelijkheid van oppervlakten op die manier aan te tonen. Vraag me gerust om een demo tijdens een PGG-meeting.

**Comment by PHengst** [comment]
@yustarandomname  is this a duplicate?
