### ISSUE TITLE
[New image]: Interactive picture least squares version 1

### ISSUE THREAD

**Issue by VandeBult** [PRIME-TU-Delft/Open-LA-Applets#166]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter7/LeastSquares.html#fig-leastsquares-bestlines

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

https://dbalague.pages.ewi.tudelft.nl/openlabook/_images/Fig-LeastSquares-BestLines.svg

### Requirements

Not all points at the same x-coordinate

### What elements are interactive?

We only consider the picture on the right-hand side of Fig 7.5.
Make the points fixed, but different from those of picture 7.5 (otherwise the best line is already clear). Let students drag & drop 2 points which define a line and show this line. Show the vertical distances and the sum of the squares of the vertical distances. 

### Steps to completion:

- [ ] assign yourself & check labels
- [ ] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by juliavdkris** [comment]
(Will be placed in place of figure 7.8)

**Comment by PHengst** [comment]
- [ ]  ell should be capital L for the lines
