### ISSUE TITLE
[Issue]: Applet titles

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#182]
### What needs to change?

Roughly **half** of all applets currently have titles that are displayed when they are in full screen. These titles give a short description of the principle an applet tries to explain, or what example an applet illustrates.

Figure labels are not automatically added as titles, as can be seen [here](https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-parametriclinespace) or in embedded 2D applets.

 We have discussed with the PGG if it is desirable to have titles for the remaining applets, and have decided it is. It has also been decided that the current figure descriptions from the book are too long for a title, so titles for applets must manually be written and added.

TODO:

- [ ] write titles for each applet that doesnt have one
- [ ] have them reviewed

**Comment by yustarandomname** [comment]
closes #25

**Comment by JarnoBerger** [comment]
Dont think we are doing this anymore

**Comment by yustarandomname** [comment]
closed because #243 is merged
