### ISSUE TITLE
[Feature]: sync applet state to caption in the book

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#188]
We can use [`Window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communicate data from inside an iframe to its parent. Then we can run some JavaScript code in the book that updates the captions

**Comment by yustarandomname** [comment]
Is no longer in active development. If development is picked up again, reopen this issue.
