### ISSUE TITLE
New: innerproduct-perp-non-perp

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#35]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#fig-innerproduct-perp-non-perp

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/221691867-de6e9dae-6fd8-4de6-9b3a-649c420537c3.png)

### Requirements

None

### What elements are interactive?

Combine the two images into one, v1 does not move and you can drag v2 (or use a slider) to change the angle beween v1 and v2. The applet should 'click' and show the 90 degrees symbol when v1 and v2 are perpendicular.

**Comment by yustarandomname** [comment]
Closed because no interaction is beneficial for the book
