### ISSUE TITLE
New: innerproduct-perpendicularline

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#37]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#fig-innerproduct-perpendicularline

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/221693463-400bbbf3-3c3e-4cae-91dc-7ab99142c330.png)

### Requirements

n must be orthogonal to L

### What elements are interactive?

Very simple: drag n , L moves with it.

**Comment by yustarandomname** [comment]
- [ ] Shouldn't n be "normalised"

**Comment by yustarandomname** [comment]
@ChristopheTUD @VandeBult Do we want n to rotate around the origin or n be draggable in the 2d space?

**Comment by yustarandomname** [comment]
N has minimum length of 1 ish
