### ISSUE TITLE
New: innerproduct-projectionvectorline

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#38]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#fig-innerproduct-projectionvectorline

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/221694692-ee594ded-460a-4c0d-93d2-2c52c0150b8a.png)

### Requirements

orthogonal projection, so (w -ŵ) orthogonal to v

### What elements are interactive?

Move the vector v (which changes the rotation of line L). W's projection ŵ changes with v and L.

**Comment by yustarandomname** [comment]
dsglkjgdfs;lkjfgsl;kj ik ben het niet eens 😠

**Comment by VandeBult** [comment]
$\begin{pmatrix} a & b \\ c & d\end{pmatrix} $

**Comment by yustarandomname** [comment]
is already merged in the book
