### ISSUE TITLE
New: innerproduct-triangleinequality

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#39]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/221856472-c9e5feb3-8942-4924-9d71-bff7d0022fc7.png)

### Requirements

|v+w |<=| v| + |w|

### What elements are interactive?

W of v draggen in alle richtingen, highlight de situatie van de driekhoek ongelijkheid.

**Comment by yustarandomname** [comment]
is already implemented and merged in the book
