### ISSUE TITLE
Theorem 1.1 (static 2D image)

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#40]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter1/Inner_Product.html#norm-in-mathbb-r-n

### What type of applet is this?

Static image

### What state is the static image?

No, Dennis has not created a static image yet

### Static image

There should be an image here that shows that this theorem is pythagoras theorem. (or simply a link to or copy of fig 1.6?)

### Requirements

None

### What elements are interactive?

None

**Comment by yustarandomname** [comment]
- [ ] The textbook should be updated to refer back to the images that came before. No new applets are needed
