### ISSUE TITLE
Proposition 1.12 (slideshow)

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#44]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Cross_Product.html#the-cross-product

### What type of applet is this?

Interactive slide show

### What state is the static image?

No, Dennis has not created a static image yet

### Static image
![image](https://user-images.githubusercontent.com/72745426/229103001-10d42f18-404d-4bba-abe3-f303c34f9b15.png)

A slideshow with 3 images, each illustrating a different part of the proposition. eg for i) a v1, v2, and -v2 with calculations of the cross product.

### Requirements

An image for each part

### What elements are interactive?

Clicking between images in the slideshow.

**Comment by yustarandomname** [comment]
Visualisation does not give any additional values. It can be opened again if a "better" (i.e. sketch or interactive elements) description of the visualisation is provided.
