### ISSUE TITLE
[Fix]: linesandplanes-parametriclinespace

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#48]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#lines-in-the-space-mathbb-r-3

### Direct link to the applet

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-parametriclinespace

### What type of applet is this?

Interactive applet 3D

### What needs to change?

1.  It should be possible to make r negative
2.  r * u is not a dot product, so the dot needs to be removed
3.  add colors to the labels to make it more readable (if possible)

**Comment by yustarandomname** [comment]
is closed in #115
