### ISSUE TITLE
[New image]: LinSystems:ReductionToRREF (example 2.20)

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#50]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearSystems.html#Ex:LinSystems:ReductionToRREF-2

### What type of applet is this?

Interactive slide show

### What state is the static image?

No, Dennis has not created a static image yet

### Static image

No image, just shows matrices and applications of row reductions

### Requirements

must follow example

### What elements are interactive?

There are many row reducing operations , we want this to become a slide show which incorperate/ is similar to exisitng prime applet that does row manipulations:
https://prime-applets.ewi.tudelft.nl/apps/linear-algebra/linear-systems/

**Comment by yustarandomname** [comment]
It is built in a combination PR #245.

The applet is split into two 
- src/routes/applet/linear_systems/row_reduction_1/+page.svelte
- src/routes/applet/linear_systems/row_reduction_2/+page.svelte
