### ISSUE TITLE
[New image]:  Example 2.24 (No title)

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#52]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearCombinations.html#:~:text=systems%20of%20equations.-,Example%202.24,-%EF%BF%BD

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

A 3d image that models the given vectors and has sliders for the coefficients x1 and x2

### Requirements

must follow example

### What elements are interactive?

Once you put the sliders in the correct positions (when x1*v1 +x2*v2 = b), confetti appears  🎊 

### Does this issue relate or depend on other issues?

No

**Comment by yustarandomname** [comment]
Is already resolved in a different issue #154 and is thus closed
