### ISSUE TITLE
[Fix]: linear_combinations/span_two_plane

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#54]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearCombinations.html#fig-linearcombinations-spantwovectors

### Direct link to the applet

https://openla.ewi.tudelft.nl/applet/linear_combinations/span_two_plane

### What type of applet is this?

Interactive applet 3D

### What needs to change?

Add two sliders that move u an v around the span(u, v),

**Comment by RensDur** [comment]
Be careful: if u and v point in the same direction, we have a problem because they no longer span a plane.
