### ISSUE TITLE
[Fix]: lintrafo-embedr2r3

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#61]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter3/Linear_Transformations.html#fig-lintrafo-embedr2r3

### Direct link to the applet

https://deploy-preview-28--playful-otter-9e0500.netlify.app/applet/linear_transformation/embed_r2_r3

### What type of applet is this?

Interactive applet 3D

### What needs to change?

No sliders! drag and drop v on the left side (2d) of the applet, and have the 3D part move with it .
Also: add a toggle on such that the plane span(e1, e2) can be shown/removed (shows the embedding R2).

### Does this issue relate or depend on other issues?

#28 (P5 svelte) the applet currently lives on this branch

**Comment by juliavdkris** [comment]
I'm currently working on 2D drag-and-drop functionality :)
