### ISSUE TITLE
[New image]: basisdim-standardbasis

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#65]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter4/BasisAndDimension.html#fig-basisdim-standardbasis

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/227259564-0875ecb4-ba80-4f31-85af-5eb8ea8f6fd3.png)

### Requirements

none

### What elements are interactive?

3D part of the image can turn

**Comment by yustarandomname** [comment]
After feedback from the teachers:
- [ ] Remove the $T(e_n) -> e_n$
- [ ] Color the $e_1, e_2, e_3$
