### ISSUE TITLE
[Fix image]: changeofbasis-projection

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#66]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter4/ChangeOfBasis.html#fig-changeofbasis-projection

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/230373419-c7581b38-c006-4245-bc55-5ad9510e6c73.png)

### Requirements

must follow the example

### What elements are interactive?

Rotation for a 3d applet

**Comment by PHengst** [comment]
duplicate

**Comment by yustarandomname** [comment]
- [ ] Vectoren van de text pakken (niet loodrecht)
- [ ] Groene stippel lijn eruit
- [ ] en rode lijnen 
- [ ] Start hoek zoals dit ongeveer
<img width="715" alt="image" src="https://github.com/PRIME-TU-Delft/Open-LA-Applets/assets/25432790/7d91dd57-9810-45c9-bced-f7c170bac5d3">

- [ ] Zelfde voor statisch
