### ISSUE TITLE
[New image]: detgeometric-paraped

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#68]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter5/DeterminantsGeometric.html#fig-detgeometric-paraped

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/227262768-b705d520-30bc-49e4-ace5-c97aa65c65bb.png)

### Requirements

Volume equals base area times height

### What elements are interactive?

Must be able to rotate around the 3D figure.

**Comment by yustarandomname** [comment]
try to fill in the parallelopiped
