### ISSUE TITLE
[New image]: ortho-orthocomp

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#69]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter7/Orthogonality.html#fig-ortho-orthocomp

### What type of applet is this?

None

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/227264886-3461a0c0-520f-4aa2-8173-1a7518a03236.png)

### Requirements

None

### What elements are interactive?

The right side of this image is 3d, so needs to be able to rotate.

**Comment by JarnoBerger** [comment]
change v to mathcal v
