### ISSUE TITLE
[New image]: ortho-orthodecomp

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#71]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter7/Orthogonality.html#fig-ortho-orthodecomp

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/227265933-1d55de8d-3165-4d89-a5d8-dbf6c3aa1e73.png)

### Requirements

none

### What elements are interactive?

Must be 3D and rotateable.

**Comment by JarnoBerger** [comment]
change v to matchcal v
