### ISSUE TITLE
[New image]: linesandplanes-twodisjointplanes

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#81]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-twodisjointplanes

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/234573329-422ffc4b-d46a-4eb7-9aa6-387632079a17.png)

### Requirements

none

### What elements are interactive?

rotate around image, student is able to move planes

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [X] embed the image in the book (with review status)
- [X] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by yustarandomname** [comment]
is embedded
