### ISSUE TITLE
[New image]: linesandplanes-planespointintersection

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#83]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-planespointintersection

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/234574603-368cb1ed-9d14-42a8-b334-c276d4d53663.png)

### Requirements

none

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [X] embed the image in the book (with review status)
- [X] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by yustarandomname** [comment]
is embedded
