### ISSUE TITLE
[New image]: linesandplanes-normalequationplane

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#84]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-normalequationplane

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234574665-72dc9653-06c7-4388-9ac5-b4f4fac27098.png)

### Requirements

P = (0,2,1), Q is arbitrary, n is orthogonal to PQ

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [X] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by yustarandomname** [comment]
is embeded
