### ISSUE TITLE
[New image]: linesandplanes-twoplaneslineintersection

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#88]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-twoplaneslineintersection

### What type of applet is this?

Interactive applet 3D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234577778-9089577a-39a6-4682-8ed8-3e12afdf000f.png)

### Requirements

None

### What elements are interactive?

Both planes can be rotated along the line of intersection

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [X] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by yustarandomname** [comment]
Has negative axis -> Approved
