### ISSUE TITLE
[Fix]: https://openla.ewi.tudelft.nl/applet/vectors/3Daddition

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#89]
### Link to paragraph

https://openla.ewi.tudelft.nl/applet/vectors/3Daddition

### Direct link to the applet

https://openla.ewi.tudelft.nl/applet/vectors/3Daddition

### What type of applet is this?

Interactive applet 3D

### What needs to change?

- [x] The start view of the applet is not ideal
- [x] The vectors labels overlap alot with the vectors themselves, cluttering the image

### Steps to completion:

- [ ] assign yourself & check labels
- [ ] implement changes described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by TeunJa** [comment]
After review with Christophe, we have the following additional comments
- Axis are x,y and z. Not formally introduced in book (nothing actually is introduced about 3D axis in the book. In 2D, they introduce x and y)
- [ ] Vectors can be placed above the endpoint to make it more readible.
- [ ] x,y,z on both sides (would do one side), numbering in this case not necessary (delete it only tiks for readibility).
