### ISSUE TITLE
[New image]: changeofbasis-triangulargrid

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#91]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter4/ChangeOfBasis.html#fig-changeofbasis-triangulargrid

### What type of applet is this?

Interactive applet 3D

### Link to applet

https://openla.ewi.tudelft.nl/applet/change_of_basis/triangular_grid

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234615584-576e6fe0-8e64-46e9-9661-805148dd87e1.png)

### Requirements

None

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by ChristopheTUD** [comment]
Does this need to be an applet? Right now only zoom is possible. The vectors b1 and b2 are also slightly longer than in the example.

**Comment by yustarandomname** [comment]
No interactivity is needed and is thus marked as "not planned"
