### ISSUE TITLE
[Fix]: geomlintrans-3dproj

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#92]
### Link to paragraph

https://prime.pages.ewi.tudelft.nl/openlabook/Chapter3/GeometryofLinearTransformations.html#fig-geomlintrans-3dproj

### What type of applet is this?

Interactive applet 3D

### Link to applet

https://openla.ewi.tudelft.nl/applet/geom_lin_trans/3d_proj_on_line

### What state is the static image?

No, Dennis has not created a static image yet

### Static image

N/A

### Requirements

None

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [x] embed the image in the book (with review status)
- [x] get feedback from the math teachers
- [x] get feedback from writers
- [x] remove review status in book

**Comment by ChristopheTUD** [comment]
x,y,z
Line is denoted "Line(L)" where just "L" would be sufficient.

**Comment by yustarandomname** [comment]
- [ ] There is no right image although it is expected by the caption

Should be reviewed by PGG after
