### ISSUE TITLE
[New image]: linearcombinations-spanonevectors

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#95]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearCombinations.html#fig-linearcombinations-spanonevectors

### What type of applet is this?

Interactive applet 3D

### Link to applet

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearCombinations.html#fig-linearcombinations-spanone

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234623998-244ed7e5-5bc8-4de9-ab89-1ac152344ec6.png)

### Requirements

None

### Steps to completion:

- [X] assign yourself & check labels
- [ ] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by ChristopheTUD** [comment]
The link to the applet is incorrect, it should be https://openla.ewi.tudelft.nl/applet/linear_combinations/span_one
Axes are labelled x, y, z rather than x1, x2, x3.

**Comment by PHengst** [comment]
From a duplicate issue describing feedback: \

- [ ] this applet needs to be made interactive, there must be a slider of a point p (on the line span{v} ) such that it moves over the line Span{v}.
