### ISSUE TITLE
[New image]: linearcombinations-spantwoparallelvectors

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#97]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter2/LinearCombinations.html#fig-linearcombinations-spantwoparallelvectors

### What type of applet is this?

Interactive applet 3D

### Link to applet

https://openla.ewi.tudelft.nl/applet/linear_combinations/span_two_line

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234625358-a9632cf8-72f0-4de3-9d4c-bd11cd0e325f.png)

### Requirements

None

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by ChristopheTUD** [comment]
Matching colours (yellow, red) for u and v?
